name: kotlin_flavor
description: An utility package for providing static extension methods familiar in Kotlin.
version: 0.1.0
author: YusukeIwaki
homepage: https://github.com/YusukeIwaki/dart-kotlin_flavor
repository: https://github.com/YusukeIwaki/dart-kotlin_flavor

environment:
  sdk: ">=2.6.0-dev.6.0 <3.0.0"

dev_dependencies:
  test: ^1.9.3
